services:
  tsdproxy:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: tsdproxy
    ports:
      - 81:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdata:/data
      - ../dev/tsdproxy-local.yaml:/config/tsdproxy.yaml:ro
      - ../dev/KEY_FILE:/config/KEY_FILE:ro
      - ../dev/file1.yaml:/config/file1.yaml:ro
    environment:
      - TSNET_FORCE_LOGIN=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - c2
    restart: unless-stopped

  c1:
    image: nginx:latest
    ports:
      - 91:80
      - 92:8000
      - 93:8080
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=testeff
      - tsdproxy.ephemeral=true
      - tsdproxy.funnel=true
      - tsdproxy.container_port=80
      - tsdproxy.dash.visible=true
      # - tsdproxy.port.1=443/https:80/http, no_autodetect
    # networks:
    # - c1

  c2:
    image: nginx:1.27
    ports:
      - 82:80
    labels:
      - tsdproxy.enable=true
      # - tsdproxy.port.1=443/https:80/http
    networks:
      - c2

  c3:
    image: nginxinc/nginx-unprivileged:latest
    ports:
      - 83:8080
    labels:
      - tsdproxy.enable=true
      - tsdproxy.autodetect=true
      # - tsdproxy.port.1=443/https:8080/http
    # networks:
    #   - c2

  s1:
    image: nginx
    ports:
      - 101:80
      - 102:8000
      - 103:8080
    deploy:
      labels:
        - tsdproxy.enable=true
        - tsdproxy.name=testeff
        - tsdproxy.ephemeral=true
        - tsdproxy.funnel=true
        - tsdproxy.container_port=80
        - tsdproxy.dash.visible=true
    networks:
      - c1

  s2:
    image: nginx
    ports:
      - 112:80
    deploy:
      labels:
        - tsdproxy.enable=true
    networks:
      - c2

  s3:
    image: nginx
    network_mode: host
    ports:
      - 113:80
    deploy:
      labels:
        - tsdproxy.enable=true

volumes:
  tsdata:
  tmp:

networks:
  c1:
  c2:
